import importlib
import os

import settings

try:
    import config as config_source  # generated by setup.py, may be absent
except ModuleNotFoundError:
    import config_def as config_source


def reload_settings():
    return importlib.reload(settings)


def test_exposes_values_from_active_config_source(monkeypatch):
    # settings must expose config.py's values when present, otherwise fall
    # back to config_def (paths aside).
    monkeypatch.delenv("DSB_DATADIR", raising=False)
    monkeypatch.delenv("DSB_WEBDIR", raising=False)
    mod = reload_settings()
    assert mod.count == config_source.count
    assert mod.ctsns == config_source.ctsns
    assert mod.copyrighttoken == config_source.copyrighttoken
    assert mod.tokenlength == config_source.tokenlength


def test_falls_back_to_config_def_when_config_absent(monkeypatch):
    import sys

    class BlockConfig:
        def find_spec(self, name, path=None, target=None):
            if name == "config":
                raise ModuleNotFoundError("No module named 'config'", name="config")
            return None

    monkeypatch.delenv("DSB_DATADIR", raising=False)
    monkeypatch.delenv("DSB_WEBDIR", raising=False)
    monkeypatch.delitem(sys.modules, "config", raising=False)
    monkeypatch.setattr(sys, "meta_path", [BlockConfig()] + sys.meta_path)
    import config_def

    mod = reload_settings()
    assert mod.count == config_def.count
    assert mod.ctsns == config_def.ctsns


def test_env_override_wins(monkeypatch, tmp_path):
    monkeypatch.setenv("DSB_DATADIR", str(tmp_path / "data"))
    monkeypatch.setenv("DSB_WEBDIR", str(tmp_path / "web"))
    mod = reload_settings()
    assert mod.datadir == str(tmp_path / "data") + os.sep
    assert mod.webdir == str(tmp_path / "web") + os.sep


def test_datadir_is_absolute_regardless_of_cwd(monkeypatch, tmp_path):
    monkeypatch.delenv("DSB_DATADIR", raising=False)
    monkeypatch.delenv("DSB_WEBDIR", raising=False)

    monkeypatch.chdir(tmp_path)
    mod = reload_settings()
    from_tmp = mod.datadir

    monkeypatch.chdir(os.path.dirname(__file__))
    mod = reload_settings()
    from_tests = mod.datadir

    assert os.path.isabs(from_tmp)
    assert from_tmp == from_tests  # anchored on the etl folder, not the cwd


def test_dirs_end_with_separator(monkeypatch):
    monkeypatch.delenv("DSB_DATADIR", raising=False)
    monkeypatch.delenv("DSB_WEBDIR", raising=False)
    mod = reload_settings()
    assert mod.datadir.endswith(os.sep)
    assert mod.webdir.endswith(os.sep)
